name: test_django

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: checkout-code
        uses: actions/checkout@v5
      - name: setup_python
        uses: actions/setup-python@v6
        with:
          python-version: ${{matrix.python-version}}

      - name: install_dependencies
        run: |
          python -m pip install --upgrade pip
          pip install  -r requirements.txt

      - name: run_tests
        run: python manage.py test
